<?php
$names=$_POST['names'];
$password=$_POST['password'];
$email=$_POST['email'];
$age=$_POST['Age'];
$date=$_POST['date'];
$status=$_POST['status'];
$gender=$_POST['gender'];
$level=$_POST['level'];
$file=$_POST['file'];
$textarea=$_POST['textarea'];
$color=$_POST['color'];
$datetime=$_POST['datetime-local'];
$hidden=$_POST['hidden'];
$month=$_POST['month'];
$range=$_POST['range'];
$search=$_POST['search'];
$tel=$_POST['tel'];
$text=$_POST['text'];
$time=$_POST['time'];
$url=$_POST['url'];
$week=$_POST['week'];
echo "Your names are $names";
echo "<br/>";
echo "your password is $password ";
echo "<br/>";
echo "your email is  $email ";
echo "<br/>";
echo "your age is $age "; 
echo "<br/>";
echo "your date of birth is $date ";
echo "<br/>";
echo "Your status is $status ";
echo "<br/>";
echo "Your gender is $gender ";
echo "<br/>";
echo "You are in $level ";
echo "<br/>";
echo "You have uploaded $file ";
echo "<br/>";
echo "You said $textarea as a feedback ";
echo "<br/>";
echo "You preferer this colour $color ";
echo "<br/>";
echo "You wish to get interviewed on $datetime ";
echo "<br/>";
 echo "$hidden"; 
 echo "<br/>";
 echo "You wish to have holidays on $month ";
 echo "<br/>";
 echo "You rated $range to our website ";
 echo "<br/>";
 echo "You entered $search in the search bar ";
 echo "<br/>";
 echo " $tel this is your phone number ";
 echo "<br/>";
 echo " $text ";
 echo "<br/>";
 echo "You current time is $time ";
 echo "<br/>";
 echo "You entered $url as a URL";
 echo "<br/>";
 echo "Your starting week is $week ";
 echo "<br/>";
?>